GLOBAL_INFILE_SUFFIX = 'bdatbx'

DB_SOURCE_URI = '__src_uri'
DB_SOURCE_TAGS = '__src_tags'
DB_SOURCE_COLL = '__src_collection'
DB_DL_RESCODE = '__dl_rescode'
DB_DL_ERROR = '__dl_error'
DB_DL_DOMAIN = '__dl_domain'
DB_DL_RAWFILE = '__dl_rawfilepath'
DB_DL_RAWFILESIZE = '__dl_rawfilesize'
DB_TE_WC = '__te_tokencount'
DB_TE_RAWFILE = '__te_rawfilepath'
DB_TE_RAWFILESIZE = '__te_rawfilesize'
DB_LANG_AUTO = '__lang_auto'
